import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Explicit, not autogenerated: the grouping is editorial. It mirrors how
 * `docs/index.md` already organises the material, and a new document should be
 * placed deliberately rather than appearing wherever the filename happens to sort.
 */
const sidebars: SidebarsConfig = {
  planning: [
    'index',
    {
      type: 'category',
      label: 'Program',
      collapsed: false,
      items: [
        'roadmap',
        'system-architecture',
        'glossary',
        'reground-2026-09-15-design',
        'docs-overhaul-2026-09-16-design',
      ],
    },
    {
      type: 'category',
      label: 'How work gets done',
      collapsed: false,
      items: ['ralph-loop-process', 'review-process', 'ralph-loop-efficiency'],
    },
    {
      type: 'category',
      label: 'Identity and auth domain',
      items: [
        'idp-rbac-comparison',
        'identity-capability-gap-analysis-2026-09-05',
        'descope-data-model',
        'oidc-certification-analysis',
        'ory-sso-provider-context',
        'ory-iac-automation-plan',
      ],
    },
    {
      type: 'category',
      label: 'Governed brain',
      items: [
        'governed-brain-where-it-stands',
        'governed-brain-concepts',
        'governed-brain-architecture',
        'governed-brain-authorization',
        'governed-brain-implementation-plan',
        {
          type: 'category',
          label: 'Research',
          items: [
            'research/governed-brain-research-2026-09-15',
            'research/governed-brain-research-2026-09-15-standards',
            'research/governed-brain-research-2026-09-15-agent-protocols',
            'research/governed-brain-research-2026-09-15-agent-memory',
            'research/governed-brain-research-2026-09-15-relationship-authorization',
            'research/governed-brain-research-2026-09-15-vendor-agent-identity',
            'research/governed-brain-research-2026-09-15-receipts',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Parked ideas',
      items: ['idea-open-identity', 'ideas'],
    },
  ],
};

export default sidebars;
